---
name: Build disk image
on:
  schedule:
    - cron: "0 1 * * TUE"
  workflow_dispatch:

jobs:
  build_release:
    name: Build and release disk image
    permissions:
      contents: read
      packages: read
      id-token: write
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        platform: ["amd64", "arm64"]
    runs-on: ${{ matrix.platform == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true

      - name: Maximize build space
        if: inputs.platform != 'arm64'
        uses: ublue-os/remove-unwanted-software@cc0becac701cf642c8f0a6613bbdaf5dc36b259e # v9
        with:
          remove-codeql: true

      - name: Pull image
        run:  sudo podman pull ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      - name: Build ISO
        id: build-iso
        uses: osbuild/bootc-image-builder-action@main
        with:
          config-file: './build_files/iso.toml'
          image: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          types: anaconda-iso
          rootfs: btrfs
          additional-args: --use-librepo=False

      - name: Upload Artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v5
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.platform }}
          path: ${{ steps.build-iso.outputs.output-directory }}
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true
